services:
  # Add Nginx reverse proxy
  nginx-proxy:
    image: nginx:alpine
    container_name: ecis-nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ecis-network
      - proxy-network
    depends_on:
      - ecis-solutions
      - ecis-backend

  # Update frontend to not expose port directly
  ecis-solutions:
    ports: []  # Remove direct port exposure
    networks:
      - ecis-network
      - proxy-network

  # Update backend to not expose port directly  
  ecis-backend:
    ports: []  # Remove direct port exposure
    networks:
      - ecis-network
      - proxy-network
